blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³
    url: https://github.com/catnip-evergreen/lab-github-cicd-demo/discussions
    about: è³ªå•ã‚„è­°è«–ã¯ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³ã§è¡Œã†ã“ã¨ã‚‚ã§ãã¾ã™
  - name: ğŸ“– ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
    url: https://github.com/catnip-evergreen/lab-github-cicd-demo/blob/main/README.md
    about: README ã‚„ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆã‚’ç¢ºèªã—ã¦ãã ã•ã„
